dpr_base_url: "https://dpr-backend/export/dynamic/pamela_srv?"
dpr_query: "filter=HOST_ID%3A{{ inventory_hostname_short | upper }}&fields=APPLICATION_NAME_VALUE%2CHOST_ID%2CAPPLICATION_BAM_VALUE%2CAPPLICATION_AUID_VALUE&format=json"

opensearch_host: "https://elk-platform-es.org"
opensearch_index: "{{ data_env }}-middle-products"
opensearch_path: "_update_by_query"
opensearch_qs: "pretty&refresh"
opensearch_url: "{{ opensearch_host }}/{{ opensearch_index }}/{{ opensearch_path }}?{{ opensearch_qs }}"

elastic_url: https://elk-platform-es.org

organization_id: 6
scm_credential_id: 123
project_id: 3332 ##REVISAR y cambiar

instance_groups_id:
  EMEA: 1
  AMER: 6
  APAC: 7

allowed_inventories:
  apache: "apache.ini"
  sso: "sso.ini"
  tomcat: "tomcat.ini"
  weblogic: "weblogic.ini"

product_playbook:
  apache: "apache.yml"
  sso: "sso.yml"
  tomcat: "tomcat.yml"
  weblogic: "weblogic.yml"

ini_dir: "inventories"

product_ini_files:
  apache:
    - "apache.ini"
    - "apache_sso_ibm_vdc.ini"
  tomcat:
    - "tomcat.ini"
  weblogic:
    - "weblogic.ini"

region_credentials:
  emea: 21
  apac: 30
  amer: 26
  dmzi: 24
  ets: 146

selected_cred_id: "{{ region_credentials[region] }}"
