---
project_branch: "feature/tower-inventory-templates"

product_ini_files:
  apache:
    - "apache.ini"
    - "apache_sso_ibm_vdc.ini"
  tomcat:
    - "tomcat.ini"
  weblogic:
    - "weblogic.ini"

product_playbook:
  apache: "apache.yml"
  sso: "sso.yml"
  tomcat: "tomcat.yml"
  weblogic: "weblogic.yml"

region_credentials:
  emea: 21
  apac: 30
  amer: 26
  dmzi: 24
  ets: 146

selected_cred_id: "{{ region_credentials[region] }}"
