---
- name: "Normalize product"
  set_fact:
    product_lc: "{{ product | lower }}"

- name: "Validate product"
  assert:
    that:
      - product_lc in product_playbook
      - product_lc in allowed_inventories

- name: "Select playbook_to_run and ini_files (single)"
  set_fact:
    playbook_to_run: "{{ product_playbook[product_lc] }}"
    ini_files:
      - "{{ allowed_inventories[product_lc] }}"

- name: "Normalize inventory_name"
  set_fact:
    inventory_name: "{{ inventory_name | lower }}"

- name: "Validate inventory_name"
  assert:
    that:
      - inventory_name in allowed_inventories

- name: "Select single ini_file"
  set_fact:
    ini_files:
      - "{{ allowed_inventories[inventory_name] }}"

- name: "Create adhoc inventory"
  uri:
    url: "{{ ansible_url }}/inventories/"
    method: POST
    status_code: [200, 201]
    headers:
      Accept: application/json
      Authorization: "Bearer {{ svc_token }}"
    validate_certs: false
    body_format: json
    body:
      name: "{{ adhoc_tag }}"
      organization: "{{ organization_id | int }}"
  register: inv
  become: false

- name: "Set inventory_id"
  set_fact:
    inventory_id: "{{ inv.json.id }}"

- name: "Check how many hosts are present in the inventory"
  uri:
    url: "{{ ansible_url }}/inventories/{{ inventory_id }}/hosts/"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ svc_token }}"
    validate_certs: false
  register: host_check
  ignore_errors: true
