---
- name: "Create SCM sources for INI files"
  uri:
    url: "{{ ansible_url }}/inventories/{{ inventory_id }}/inventory_sources/"
    method: POST
    status_code: [200, 201]
    headers:
      Accept: application/json
      Authorization: "Bearer {{ svc_token }}"
    validate_certs: false
    body_format: json
    body:
      name: "{{ adhoc_tag }}-src-{{ item | basename }}"
      inventory: "{{ inventory_id | int }}"
      source: "scm"
      source_project: "{{ project_id | int }}"
      source_path: "{{ ini_dir }}/{{ item }}"
      update_on_launch: true
  loop: "{{ ini_files }}"
  register: sources
  become: false

- name: "Capture source ids"
  set_fact:
    inventory_source_ids: "{{ sources.results | map(attribute='json.id') | list }}"

- name: "Debug - source ids captured"
  debug:
    msg: "Source ID of inventory(s): {{ inventory_source_ids }}"

- name: "Show host count (debug)"
  uri:
    url: "{{ ansible_url }}/inventories/{{ inventory_id }}/hosts/"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ svc_token }}"
    validate_certs: false
  register: host_list
  become: false

- name: "Debug - how many hosts are in the inventory"
  debug:
    msg: "Inventory {{ inventory_id }} contains {{ host_list.json.count }} host(s)"
