---
- name: "Build extra_vars"
  set_fact:
    extra_vars_dict:
      region: "{{ region }}"
      location: "{{ location }}"
      patch_envs: "{{ patch_envs }}"
      patch_product: "{{ patch_product }}"
  become: false

- name: "Create adhoc job template"
  uri:
    url: "{{ ansible_url }}/job_templates/"
    method: POST
    status_code: [200, 201]
    headers:
      Accept: application/json
      Authorization: "Bearer {{ svc_token }}"
    validate_certs: false
    body_format: json
    body:
      name: "{{ adhoc_tag }}"
      job_type: "run"
      inventory: "{{ inventory_id | int }}"
      project: "{{ project_id | int }}"
      playbook: "{{ playbook_to_run }}"
  register: adhoc_template
  become: false

- name: "Set adhoc_template_id"
  set_fact:
    adhoc_template_id: "{{ adhoc_template.json.id }}"
