---
- name: "Normalize region for credential map"
  set_fact:
    region_lc: "{{ region | lower }}"

- name: "Assert region"
  assert:
    that:
      - region_lc in ['emea','apac','amer']

- name: "Select credential"
  set_fact:
    cred_id: >-
      {{
        (location | upper) == 'DMZI' | ternary(region_credentials['dmzi'],
        (location | upper) == 'ETS'  | ternary(region_credentials['ets'],
        region_credentials[region_lc]))
      }}
