---
- name: "Set region (emea|apac|amer) from launch_limit"
  set_fact:
    region: "{{ (launch_limit | lower | regex_search('(emea|apac|amer)')) | default('', true) }}"

- name: "Assert region"
  assert:
    that:
      - region in ['emea','apac','amer']

- name: "Select credential"
  set_fact:
    cred_id: >-
      {{
        (location | upper) == 'DMZI' | ternary(region_credentials['dmzi'],
        (location | upper) == 'ETS'  | ternary(region_credentials['ets'],
        region_credentials[region]))
      }}